name: "Update README with Jinja2"

on:
  schedule:
    - cron: "15 */6 * * *" # runs every 6 hours at 15 minutes past the hour - change as needed
  push:
    branches:
      - "main"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2
      - name: Run Jinja2 script
        run: python update_readme.py
      - name: Commit and push
        run: |
          git config user.name SuhravHussen
          git config user.email suhravshan@gmail.com
          git add README.md
          git commit -m "Update README.md with dynamic content"
          git push origin main
