name: Update README with Javascript

on:
  schedule:
    - cron: "15 */6 * * *" # runs every 6 hours at 15 minutes past the hour
  push:
    branches:
      - "main"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies and update readme
        env:
          BASEURL: ${{ secrets.BASEURL }}
        run: |
          npm install mustache
          node update_readme.js
          
      - name: Commit and push changes
        run: |
          git config user.name "SuhravHussen"
          git config user.email "suhravshan@gmail.com"
          git add .

          if git diff --cached --exit-code; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "update readme"
            git push origin main
          fi
