name: Update README with Javascript

on:
  schedule:
    - cron: "15 */6 * * *" # runs every 6 hours at 15 minutes past the hour - change as needed
  push:
    branches:
      - "main"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js and update readme
        env:
          BASEURL: ${{ secrets.BASEURL }}
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 20
          nvm use 20
          npm install mustache
          node update_readme.js
      - name: Commit and push
        run: |
          git config user.name SuhravHussen
          git config user.email suhravshan@gmail.com
          git add .

          if git diff --cached --exit-code; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "update"
            git rebase main
            git push origin main
          fi
